// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiaRbwW2rm9uLBFBcE_SaSc8rQ3edPlnQ',
    appId: '1:730897047347:android:0e1fbc2d9e180f96422846',
    messagingSenderId: '730897047347',
    projectId: 'auth-app-94f98',
    storageBucket: 'auth-app-94f98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmN0ivGJvRfef25IrXW3cgZsX7SWbcG1E',
    appId: '1:730897047347:ios:9a0b4940d6a412c7422846',
    messagingSenderId: '730897047347',
    projectId: 'auth-app-94f98',
    storageBucket: 'auth-app-94f98.appspot.com',
    iosClientId: '730897047347-5rv9v8dvuukqhjsa89ams1ch9m57mlnj.apps.googleusercontent.com',
    iosBundleId: 'com.pallavi.ecommerceproject',
  );
}
